version: '3'

tasks:
  dev:
    deps:
      - symfony-dev
      - start-docker-dev
      - start-vite-dev

  test:
    deps:
      - start-docker-dev
      - run-tests

  symfony-dev:
    cmds:
      - symfony local:server:start

  start-vite-dev:
    cmds:
      - npm run dev

  start-docker-dev:
    cmds:
      - docker compose up -d --wait

  run-tests:
    cmds:
      - php bin/phpunit
