- hosts: servers
  become: yes
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../.."
    ansistrano_deploy_to: "/srv"
    ansistrano_keep_releases: 3
    ansistrano_shared_paths:
      - var/log
      - var/sessions
  roles:
    - { role: ansistrano.deploy }
  tasks:
    - name: Create .env.local
      copy:
        content: "APP_ENV=prod\nAPP_DEBUG=0"
        dest: "{{ ansistrano_release_path.stdout }}/.env.local"

    - name: Install Composer dependencies
      command: composer install --optimize-autoloader
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"
      environment:
        COMPOSER_ALLOW_SUPERUSER: "1"

    - name: Clear PHP cache
      command: php bin/console cache:clear --env=prod
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"

    - name: Install NPM dependencies
      command: npm install
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"

    - name: Build Vite
      command: npm run build
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"

    - name: Create database
      command: php bin/console doctrine:database:create --if-not-exists
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"

    - name: Migrate database
      command: php bin/console doctrine:migrations:migrate --no-interaction
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"

    - name: Create AI procedures and functions in the database
      command: php bin/console app:create-ai-in-db
      args:
        chdir: "{{ ansistrano_release_path.stdout }}"
