- import_playbook: bootstrap.yml
- hosts: servers
  become: yes
  vars_files:
    - vars/database.yml
  roles:
    - php
    - frankenphp
    - postgres
    - pgvector
    - rsync
    - composer
    - node
