- hosts: servers
  become: yes
  vars_files:
    - ../vars/config.yml
  tasks:
    - name: Stop the application if it is running
      shell: pkill -f "frankenphp php-server -r /srv/current/public --domain {{ domain }}"
      args:
        chdir: /srv/current
      ignore_errors: yes

    - name: Start the application
      shell: frankenphp php-server -r /srv/current/public --domain {{ domain }} </dev/null >/dev/null 2>&1 &
      args:
        chdir: /srv/current
      
    - name: Start the messenger worker
      shell: php bin/console messenger:consume </dev/null >/dev/null 2>&1 &
      args:
        chdir: /srv/current

    - name: Compute user vectors
      command: php bin/console app:compute-user-vectors
      args:
        chdir: /srv/current

    - name: Compute user recommendations
      command: php bin/console app:compute-user-recommendations
      args:
        chdir: /srv/current
