- name: Install GPG
  package:
    name: gnupg
    state: present

- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install PostgreSQL
  apt:
    name: postgresql-17
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Install psycopg2
  apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install ACL
  package:
    name: acl
    state: present

- name: Create PostgreSQL user
  postgresql_user:
    name: "app"
    password: "!ChangeMe!"
    role_attr_flags: CREATEDB,SUPERUSER
    state: present
  become: true
  become_user: postgres
