name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Cache setup
        uses: actions/cache@v4
        with:
          path: |
            vendor
            node_modules
            .env
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/package-lock.json', '.env.ci') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Copy .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: |
          npm install
          composer install --prefer-dist

  test:
    name: Test

    runs-on: ubuntu-latest
    
    needs:
      - setup

    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore setup cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/package-lock.json', '.env.ci') }}
          path: |
            vendor
            node_modules
            .env

      - name: Run tests
        run: task test
